### ISSUE TITLE
仙人微彩的推荐算法应该是有问题吧？

### ISSUE THREAD

**Issue by Ventulus-lab** [zhyupe/matcha-overlay#4]
首先非常感谢增加了仙人微彩推荐功能
但是试用了一段时间，就一直感觉推荐得不太对，
直到今天出了一把明显有问题的，我认为可以查看下算法是不是有问题
[redacted]
如图出来的是9428四个数，中间步骤我就觉得不太正常，不推荐中间格子就很奇怪，
到最后推荐线了，就明显有问题了，
首先它推荐第一竖列，那和第二横行理论上期望应该是一样的吧？都是可能123里出个2，结果抹茶界面上显示一个最大3913一个最小116？
然后第三横行已经出了89，求稳情况下希望789也是可以，它也没有。
然后再附上之前帖子py写的那个助手的结果，我认为那个推荐还是比较对的
![weicai](https://user-images.githubusercontent.com/76762951/168967138-8ed4d965-1054-4aa1-b702-9d9c856b17d2.PNG)

**Comment by VentulusCN** [comment]
[redacted]
这个就很明显。。正常都应该追123吧

**Comment by zhyupe** [comment]
感谢反馈。由于您的截图中包含个人角色信息，已经将相关截图删除。

**Comment by zhyupe** [comment]
![image](https://user-images.githubusercontent.com/2197479/169099907-9843af66-67d0-468c-8d38-95faccf6846a.png)
![image](https://user-images.githubusercontent.com/2197479/169099966-7914cc2c-9336-49f1-a2d9-70445c96ed32.png)
![image](https://user-images.githubusercontent.com/2197479/169100031-b3121d5a-95b4-4f11-adb0-2207fa70748d.png)
![image](https://user-images.githubusercontent.com/2197479/169100078-61f25608-8aa9-457a-bd15-89b5febcea2f.png)

已修复
